---
title: "split data"
author: "Yiran Liu"
date: "2/24/2022"
output: html_document
---

```{r}
data <- read.csv("diabetes_data_upload.csv")
``` 

```{r}
positive <- data[data$class == "Positive",]
negative <- data[data$class == "Negative",]
```

```{r}
keeps <- c("muscle.stiffness", "weakness", "visual.blurring", "Irritability", 
           "Alopecia", "Polyuria", "Polydipsia", "sudden.weight.loss", 
           "Polyphagia", "partial.paresis", "class")
```

```{r}
positive = positive[keeps]
negative = negative[keeps]
positive = positive[1:200,]
```

```{r}
sum(positive$muscle.stiffness == "No") / 200; sum(positive$muscle.stiffness == "Yes") / 200
sum(negative$muscle.stiffness == "No") / 200; sum(negative$muscle.stiffness == "Yes") / 200
```
"muscle.stiffness" 不具有参考意义

```{r}
sum(positive$weakness == "No") / 200; sum(positive$weakness == "Yes") / 200
sum(negative$weakness == "No") / 200; sum(negative$weakness == "Yes") / 200
```
"weakness" 具有参考意义

```{r}
sum(positive$visual.blurring == "No") / 200; sum(positive$visual.blurring == "Yes") / 200
sum(negative$visual.blurring == "No") / 200; sum(negative$visual.blurring == "Yes") / 200
```
"visual blurring" 具有参考意义

```{r}
sum(positive$Irritability == "No") / 200; sum(positive$Irritability == "Yes") / 200
sum(negative$Irritability == "No") / 200; sum(negative$Irritability == "Yes") / 200
```
"Irritability" 不具有参考意义

```{r}
sum(positive$Alopecia == "No") / 200; sum(positive$Alopecia == "Yes") / 200
sum(negative$Alopecia == "No") / 200; sum(negative$Alopecia == "Yes") / 200
```
"Alopecia" 不具有参考意义

```{r}
sum(positive$Polyuria == "No") / 200; sum(positive$Polyuria == "Yes") / 200
sum(negative$Polyuria == "No") / 200; sum(negative$Polyuria == "Yes") / 200
```
"Polyuria" 具有参考意义

```{r}
sum(positive$Polydipsia == "No") / 200; sum(positive$Polydipsia == "Yes") / 200
sum(negative$Polydipsia == "No") / 200; sum(negative$Polydipsia == "Yes") / 200
```
"Polydipsia" 具有参考意义

```{r}
sum(positive$sudden.weight.loss == "No") / 200; sum(positive$sudden.weight.loss == "Yes") / 200
sum(negative$sudden.weight.loss == "No") / 200; sum(negative$sudden.weight.loss == "Yes") / 200
```
"sudden.weight.loss" 具有参考意义

```{r}
sum(positive$Polyphagia == "No") / 200; sum(positive$Polyphagia == "Yes") / 200
sum(negative$Polyphagia == "No") / 200; sum(negative$Polyphagia == "Yes") / 200
```
"Polyphagia" 具有参考意义

```{r}
sum(positive$partial.paresis == "No") / 200; sum(positive$partial.paresis == "Yes") / 200
sum(negative$partial.paresis == "No") / 200; sum(negative$partial.paresis == "Yes") / 200
```
"partial.paresis" 具有参考意义

"Irritability"，"muscle.stiffness"，"Alopecia" 不显著


```{r}
table(positive$muscle.stiffness)
table(positive$weakness)
table(positive$visual.blurring)
table(positive$Irritability)
table(positive$Alopecia)
table(positive$Polyuria)
table(positive$Polydipsia)
table(positive$sudden.weight.loss)
table(positive$Polyphagia)
table(positive$partial.paresis)
```

```{r}
table(negative$muscle.stiffness)
table(negative$weakness)
table(negative$visual.blurring)
table(negative$Irritability)
table(negative$Alopecia)
table(negative$Polyuria)
table(negative$Polydipsia)
table(negative$sudden.weight.loss)
table(negative$Polyphagia)
table(negative$partial.paresis)
```


